# Generated by Django 3.2.6 on 2021-08-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210804_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, choices=[('PINK', 'pink'), ('RED', 'red'), ('AQUA', 'aqua'), ('YELLOW', 'yellow'), ('GREEN', 'green'), ('GREY', 'grey'), ('CUSTOM-BLUE', 'custom-blue'), ('ORANGE', 'orange')], max_length=225, null=True),
        ),
    ]
